version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: leaflet
      - dependency-name: mapbox-gl
      - dependency-name: eslint
      - dependency-name: apexcharts
