name: Merge Review Test Build

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker image
        uses: docker://node:14.16.0

      - uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build
